<?php

function texgen_menu() {
    $item = array();

    $items['texgen'] = array(
        'title' => 'LaTeX Generator',
        'page callback' => 'texgen_page',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['texgen/doc'] = array(
        'title' => 'GenForm',
        'page callback' => 'texgen_docgen',
        'access arguments' => array('access content'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    return $items;
}

function texgen_docgenform($formstate) {
    $form['description'] = array(
        '#type' => 'item',
        '#title' => t('A form with nothing but a textfield'),
    );
    // This is the first form element. It's a textfield with a label, "Name"
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
    );
// Adds a simple submit button that refreshes the form and clears its contents -- this is the default behavior for forms.
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function texgen_docgenform_submit($form, &$form_state) {
    global $_SESSION;
    $_SESSION['tgdata'] = $form_state['values']['name'];
    
    #$form['#redirect'] = FALSE;
}


function texgen_docgen() {
    $r = drupal_get_form('texgen_docgenform');
    $r .= "<h1>D</h1><pre>";
    $r .= $_SESSION['tgdata'];
    $r .= "</pre>";

    
    return $r;
}

function texgen_submit($form, &$form_state) {
    return '<p>' . t('Your document') . ' </p>';
}

function texgen_page() {
    return '<p>' . l('LaTeX Document', 'texgen/doc') . ' </p>';
}